/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as NoEditionsRouteImport } from './routes/no-editions'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BudgetTableRouteImport } from './routes/budget-table'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const NoEditionsRoute = NoEditionsRouteImport.update({
  id: '/no-editions',
  path: '/no-editions',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetTableRoute = BudgetTableRouteImport.update({
  id: '/budget-table',
  path: '/budget-table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget-table': typeof BudgetTableRoute
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRoute
  '/no-editions': typeof NoEditionsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget-table': typeof BudgetTableRoute
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRoute
  '/no-editions': typeof NoEditionsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget-table': typeof BudgetTableRoute
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRoute
  '/no-editions': typeof NoEditionsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget-table'
    | '/dashboard'
    | '/invoices'
    | '/no-editions'
    | '/sales'
    | '/settings'
    | '/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget-table'
    | '/dashboard'
    | '/invoices'
    | '/no-editions'
    | '/sales'
    | '/settings'
    | '/auth/sign-in'
  id:
    | '__root__'
    | '/'
    | '/budget-table'
    | '/dashboard'
    | '/invoices'
    | '/no-editions'
    | '/sales'
    | '/settings'
    | '/auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetTableRoute: typeof BudgetTableRoute
  DashboardRoute: typeof DashboardRoute
  InvoicesRoute: typeof InvoicesRoute
  NoEditionsRoute: typeof NoEditionsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-editions': {
      id: '/no-editions'
      path: '/no-editions'
      fullPath: '/no-editions'
      preLoaderRoute: typeof NoEditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-table': {
      id: '/budget-table'
      path: '/budget-table'
      fullPath: '/budget-table'
      preLoaderRoute: typeof BudgetTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetTableRoute: BudgetTableRoute,
  DashboardRoute: DashboardRoute,
  InvoicesRoute: InvoicesRoute,
  NoEditionsRoute: NoEditionsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
