/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as EditionsRouteImport } from './routes/editions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BudgetTableRouteImport } from './routes/budget-table'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'

const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsRoute = EditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetTableRoute = BudgetTableRouteImport.update({
  id: '/budget-table',
  path: '/budget-table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget-table': typeof BudgetTableRoute
  '/dashboard': typeof DashboardRoute
  '/editions': typeof EditionsRoute
  '/payments': typeof PaymentsRoute
  '/sales': typeof SalesRoute
  '/auth/sign-in': typeof AuthSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget-table': typeof BudgetTableRoute
  '/dashboard': typeof DashboardRoute
  '/editions': typeof EditionsRoute
  '/payments': typeof PaymentsRoute
  '/sales': typeof SalesRoute
  '/auth/sign-in': typeof AuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget-table': typeof BudgetTableRoute
  '/dashboard': typeof DashboardRoute
  '/editions': typeof EditionsRoute
  '/payments': typeof PaymentsRoute
  '/sales': typeof SalesRoute
  '/auth/sign-in': typeof AuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget-table'
    | '/dashboard'
    | '/editions'
    | '/payments'
    | '/sales'
    | '/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget-table'
    | '/dashboard'
    | '/editions'
    | '/payments'
    | '/sales'
    | '/auth/sign-in'
  id:
    | '__root__'
    | '/'
    | '/budget-table'
    | '/dashboard'
    | '/editions'
    | '/payments'
    | '/sales'
    | '/auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetTableRoute: typeof BudgetTableRoute
  DashboardRoute: typeof DashboardRoute
  EditionsRoute: typeof EditionsRoute
  PaymentsRoute: typeof PaymentsRoute
  SalesRoute: typeof SalesRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions': {
      id: '/editions'
      path: '/editions'
      fullPath: '/editions'
      preLoaderRoute: typeof EditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-table': {
      id: '/budget-table'
      path: '/budget-table'
      fullPath: '/budget-table'
      preLoaderRoute: typeof BudgetTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetTableRoute: BudgetTableRoute,
  DashboardRoute: DashboardRoute,
  EditionsRoute: EditionsRoute,
  PaymentsRoute: PaymentsRoute,
  SalesRoute: SalesRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
