services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - garage-local

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=flower-app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
  garage-local:
    image: dxflrs/garage:v2.2.0
    restart: unless-stopped
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3903:3903"
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./garage/meta:/var/lib/garage/meta
      - ./garage/data:/var/lib/garage/data
