query getOrders(
  $editionId: Float!
  $from: String
  $to: String
  $originIds: [Float!]
) {
  orders(editionId: $editionId, from: $from, to: $to, originIds: $originIds) {
    id
    totalAmount
    executedAt
    payerFirstName
    payerLastName
    payerEmail
    helloAssoOrderId
    authorId
    originId
    origin {
      id
      name
    }
    author {
      id
      username
    }
    sales {
      id
      budgetLineId
      quantity
      unitPrice
      executedAt
      budgetLine {
        id
        name
        estimatedUnitPrice
        category {
          id
          name
          color
        }
      }
    }
  }
}
